name: 'Repo Lockdown'

on:
  pull_request_target:
    types: opened
  schedule:
    - cron: '0 * * * *'

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          pr-comment: 'This repository does not accept pull requests, thank you for your understanding.'
